.local/share/ansi-arts:
  type: archive
  url: https://api.github.com/repos/latipun7/ansi-arts/tarball
  exact: true
  stripComponents: 1
  refreshPeriod: 744h

{{ if ne .chezmoi.os "windows" -}}
.local/bin/fnm:
  # NOTE: workaround of https://github.com/actions/upload-artifact/issues/38
  type: file
  url: {{ template "fnm-download-url" . }}
  executable: true
  refreshPeriod: 168h
  filter:
    command: gzip
    args: ["-dcS", ".zip"]

.local/share/fonts/delugia-mono-complete:
  type: archive
  url: https://github.com/adam7/delugia-code/releases/latest/download/delugia-mono-complete.zip
  stripComponents: 1
  refreshPeriod: 744h

.local/share/mc/skins/dracula.ini:
  type: file
  url: https://raw.github.com/dracula/midnight-commander/master/skins/dracula.ini
  refreshPeriod: 168h

.local/share/mc/skins/dracula256.ini:
  type: file
  url: https://raw.github.com/dracula/midnight-commander/master/skins/dracula256.ini
  refreshPeriod: 168h

.local/share/omz-custom/themes/powerlevel10k:
  type: archive
  url: https://api.github.com/repos/romkatv/powerlevel10k/tarball/v{{ template "github-latest-tag" list "romkatv/powerlevel10k" .chezmoi.os }}
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.local/share/omz-custom/plugins/zsh-completions:
  type: archive
  url: https://api.github.com/repos/zsh-users/zsh-completions/tarball
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.local/share/omz-custom/plugins/zsh-syntax-highlighting:
  type: archive
  url: https://api.github.com/repos/zsh-users/zsh-syntax-highlighting/tarball
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.local/share/omz-custom/plugins/zsh-autosuggestions:
  type: archive
  url: https://api.github.com/repos/zsh-users/zsh-autosuggestions/tarball
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

www/adminer/adminer.php:
  type: file
  url: https://www.adminer.org/latest-en.php
  refreshPeriod: 744h

www/adminer/adminer.css:
  type: file
  url: https://raw.githubusercontent.com/vrana/adminer/master/designs/dracula/adminer.css
  refreshPeriod: 744h

www/adminer/plugins/plugin.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/plugin.php
  refreshPeriod: 744h

www/adminer/plugins/edit-calendar.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/edit-calendar.php
  refreshPeriod: 744h

www/adminer/plugins/edit-foreign.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/edit-foreign.php
  refreshPeriod: 744h

www/adminer/plugins/enum-option.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/enum-option.php
  refreshPeriod: 744h

www/adminer/plugins/enum-types.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/enum-types.php
  refreshPeriod: 744h

www/adminer/plugins/file-upload.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/file-upload.php
  refreshPeriod: 744h

www/adminer/plugins/pretty-json-column.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/pretty-json-column.php
  refreshPeriod: 744h

www/adminer/plugins/slugify.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/slugify.php
  refreshPeriod: 744h

www/adminer/plugins/tinymce.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/tinymce.php
  refreshPeriod: 744h

www/adminer/plugins/foreign-system.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/foreign-system.php
  refreshPeriod: 744h
{{- end }}

{{ if eq .chezmoi.os "windows" -}}
.local/bin:
  type: archive
  url: {{ template "fnm-download-url" . }}
  refreshPeriod: 168h

.local/bin/jq.exe:
  type: file
  url: https://github.com/stedolan/jq/releases/latest/download/jq-win64.exe
  executable: true
  refreshPeriod: 744h
{{- end }}

{{ if eq .chezmoi.hostname "archpi" -}}
.local/bin:
  type: archive
  url: {{ template "godns-download-url" . }}
  refreshPeriod: 168h
{{- end }}
