ansi-arts:
  type: archive
  url: https://api.github.com/repos/latipun7/ansi-arts/tarball
  exact: true
  stripComponents: 1
  refreshPeriod: 744h

{{ if ne .chezmoi.os "windows" -}}
.fnm/fnm:
  # not archive, workaround of https://github.com/actions/upload-artifact/issues/38
  type: file
  url: {{ template "fnm-download-url" . }}
  executable: true
  refreshPeriod: 168h
  filter:
    command: gzip
    args: ["-dcS", ".zip"]

.omz-custom/themes/powerlevel10k:
  type: archive
  url: https://api.github.com/repos/romkatv/powerlevel10k/tarball/v1.15.0
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.omz-custom/plugins/zsh-completions:
  type: archive
  url: https://api.github.com/repos/zsh-users/zsh-completions/tarball
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.omz-custom/plugins/zsh-syntax-highlighting:
  type: archive
  url: https://api.github.com/repos/zsh-users/zsh-syntax-highlighting/tarball
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.omz-custom/plugins/zsh-autosuggestions:
  type: archive
  url: https://api.github.com/repos/zsh-users/zsh-autosuggestions/tarball
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

www/adminer/adminer.php:
  type: file
  url: https://www.adminer.org/latest-en.php
  refreshPeriod: 744h

www/adminer/adminer.css:
  type: file
  url: https://raw.githubusercontent.com/vrana/adminer/master/designs/dracula/adminer.css
  refreshPeriod: 744h

www/adminer/plugins/plugin.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/plugin.php
  refreshPeriod: 744h

www/adminer/plugins/edit-calendar.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/edit-calendar.php
  refreshPeriod: 744h

www/adminer/plugins/edit-foreign.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/edit-foreign.php
  refreshPeriod: 744h

www/adminer/plugins/enum-option.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/enum-option.php
  refreshPeriod: 744h

www/adminer/plugins/enum-types.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/enum-types.php
  refreshPeriod: 744h

www/adminer/plugins/file-upload.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/file-upload.php
  refreshPeriod: 744h

www/adminer/plugins/pretty-json-column.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/pretty-json-column.php
  refreshPeriod: 744h

www/adminer/plugins/slugify.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/slugify.php
  refreshPeriod: 744h

www/adminer/plugins/tinymce.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/tinymce.php
  refreshPeriod: 744h

www/adminer/plugins/foreign-system.php:
  type: file
  url: https://raw.github.com/vrana/adminer/master/plugins/foreign-system.php
  refreshPeriod: 744h
{{- end }}

{{ if eq .chezmoi.os "windows" -}}
.fnm:
  type: archive
  url: {{ template "fnm-download-url" . }}
  refreshPeriod: 168h

bin/jq.exe:
  type: file
  url: https://github.com/stedolan/jq/releases/latest/download/jq-win64.exe
  executable: true
  refreshPeriod: 744h
{{- end }}

{{ if eq .chezmoi.hostname "latipun-pi" -}}
.godns:
  type: archive
  url: {{ template "godns-download-url" . }}
  stripComponents: 1
  refreshPeriod: 168h
{{- end }}
