.local/share/ansi-arts:
  type: git-repo
  url: https://github.com/latipun7/ansi-arts.git
  refreshPeriod: 744h

.config/bat/themes:
  type: archive
  url: https://github.com/catppuccin/bat/archive/refs/heads/main.zip
  stripComponents: 1
  refreshPeriod: 132h
  include: ["*/*.tmTheme"]

{{ if (and (ne .chezmoi.os "windows") (ne .chezmoi.os "android")) -}}
# ╻ ╻┏┓╻╻╻ ╻   ┏┓╻┏━┓   ┏━┓┏┓╻╺┳┓┏━┓┏━┓╻╺┳┓
# ┃ ┃┃┗┫┃┏╋┛   ┃┗┫┃ ┃   ┣━┫┃┗┫ ┃┃┣┳┛┃ ┃┃ ┃┃
# ┗━┛╹ ╹╹╹ ╹   ╹ ╹┗━┛   ╹ ╹╹ ╹╺┻┛╹┗╸┗━┛╹╺┻┛

.local/bin/vimv:
  type:  archive-file
  url: {{ template "vimv-download-url" . }}
  path: vimv
  refreshPeriod: 132h

.local/bin/fnm:
  type: archive-file
  url: {{ template "fnm-download-url" . }}
  path: fnm
  executable: true
  refreshPeriod: 132h
{{ end -}}

{{ if ne .chezmoi.os "windows" -}}
# ╻ ╻┏┓╻╻╻ ╻   ┏━┓┏┓╻╻  ╻ ╻
# ┃ ┃┃┗┫┃┏╋┛   ┃ ┃┃┗┫┃  ┗┳┛
# ┗━┛╹ ╹╹╹ ╹   ┗━┛╹ ╹┗━╸ ╹

.config/btop/themes/catppuccin-mocha.theme:
  type: file
  url: https://github.com/catppuccin/btop/raw/main/themes/catppuccin_mocha.theme
  refreshPeriod: 132h

# oh-my-zsh [[[
.local/share/oh-my-zsh:
  type: git-repo
  url: https://github.com/ohmyzsh/ohmyzsh.git
  clone:
    args: ["--depth", "1"]
  pull:
    args: ["--dry-run"] # update with `omz update`

.local/share/omz-custom/themes/powerlevel10k:
  type: archive
  url: https://github.com/romkatv/powerlevel10k/archive/refs/tags/{{ (gitHubLatestRelease "romkatv/powerlevel10k").TagName }}.tar.gz
  exact: true
  stripComponents: 1
  refreshPeriod: 132h

.local/share/omz-custom/plugins/zsh-completions:
  type: archive
  url: https://github.com/zsh-users/zsh-completions/archive/refs/heads/master.zip
  exact: true
  stripComponents: 1
  refreshPeriod: 132h

.local/share/omz-custom/plugins/zsh-syntax-highlighting:
  type: archive
  url: https://github.com/zsh-users/zsh-syntax-highlighting/archive/refs/heads/master.zip
  exact: true
  stripComponents: 1
  refreshPeriod: 132h

.local/share/omz-custom/plugins/zsh-autosuggestions:
  type: archive
  url: https://github.com/zsh-users/zsh-autosuggestions/archive/refs/heads/master.zip
  exact: true
  stripComponents: 1
  refreshPeriod: 132h

.local/share/omz-custom/plugins/zsh-autocomplete:
  type: archive
  url: https://github.com/marlonrichert/zsh-autocomplete/archive/refs/heads/main.zip
  exact: true
  stripComponents: 1
  refreshPeriod: 132h
# ]]]

# LunarVim [[[
.local/share/lunarvim/lvim:
  type: git-repo
  url: https://github.com/LunarVim/LunarVim.git
  clone:
    args: ["--depth", "1"]
  pull:
    args: ["--dry-run"] # Update via `lvim +LvimUpdate`
# ]]]

# oh-my-tmux [[[
.local/share/oh-my-tmux:
  type: git-repo
  url: https://github.com/gpakosz/.tmux.git
  refreshPeriod: 132h
  clone:
    args: ["--depth", "1"]
  pull:
    args: ["--dry-run"] # update/pull manually
# ]]]
{{ end -}}

{{ if .is_linux_gui -}}
# ╻  ╻┏┓╻╻ ╻╻ ╻   ┏━╸╻ ╻╻   ┏━┓┏┓╻╻  ╻ ╻
# ┃  ┃┃┗┫┃ ┃┏╋┛   ┃╺┓┃ ┃┃   ┃ ┃┃┗┫┃  ┗┳┛
# ┗━╸╹╹ ╹┗━┛╹ ╹   ┗━┛┗━┛╹   ┗━┛╹ ╹┗━╸ ╹

.config/zathura:
  type: archive
  url: https://github.com/catppuccin/zathura/archive/refs/heads/main.zip
  stripComponents: 2
  refreshPeriod: 132h
  include: ["*", "*/src/**"]

.config/kitty/themes/catppuccin:
  type: archive
  url: https://github.com/catppuccin/kitty/archive/refs/heads/main.zip
  stripComponents: 1
  refreshPeriod: 132h
  include: ["*/*.conf"]

.local/share/fcitx5/themes: # catppuccin-*
  type: archive
  url: https://github.com/catppuccin/fcitx5/archive/refs/heads/main.zip
  stripComponents: 2
  refreshPeriod: 132h
  include: ["*", "*/src/**"]

.config/hypr/themes:
  type: archive
  url: https://github.com/catppuccin/hyprland/archive/refs/heads/main.zip
  stripComponents: 2
  refreshPeriod: 132h
  include: ["*", "*/themes/*.conf"]
{{- end }}

{{ if .is_server -}}
# ┏━┓┏━╸┏━┓╻ ╻┏━╸┏━┓   ┏━┓┏┓╻╻  ╻ ╻
# ┗━┓┣╸ ┣┳┛┃┏┛┣╸ ┣┳┛   ┃ ┃┃┗┫┃  ┗┳┛
# ┗━┛┗━╸╹┗╸┗┛ ┗━╸╹┗╸   ┗━┛╹ ╹┗━╸ ╹

.local/bin/godns:
  type: archive-file
  url: {{ template "godns-download-url" . }}
  path: godns
  refreshPeriod: 132h

# Adminer [[[
www/adminer/adminer.php:
  type: file
  url: https://www.adminer.org/latest-en.php
  refreshPeriod: 744h

www/adminer/adminer.css:
  type: file
  url: https://raw.githubusercontent.com/Niyko/Hydra-Dark-Theme-for-Adminer/master/adminer.css
  refreshPeriod: 744h

www/adminer: # plugins
  type: archive
  url: https://github.com/vrana/adminer/archive/refs/heads/master.zip
  stripComponents: 1
  refreshPeriod: 744h
  include: ["*/plugins/**"]
# ]]]
{{- end }}

{{ if eq .chezmoi.os "windows" -}}
# ╻ ╻╻┏┓╻╺┳┓┏━┓╻ ╻┏━┓   ┏━┓┏┓╻╻  ╻ ╻
# ┃╻┃┃┃┗┫ ┃┃┃ ┃┃╻┃┗━┓   ┃ ┃┃┗┫┃  ┗┳┛
# ┗┻┛╹╹ ╹╺┻┛┗━┛┗┻┛┗━┛   ┗━┛╹ ╹┗━╸ ╹

.local/bin/fnm.exe:
  type: archive-file
  url: {{ template "fnm-download-url" . }}
  path: fnm.exe
  refreshPeriod: 132h

.local/bin/jq.exe:
  type: file
  url: https://github.com/stedolan/jq/releases/latest/download/jq-win64.exe
  executable: true
  refreshPeriod: 744h
{{- end }}

{{ if eq .chezmoi.os "android" -}}
# ┏━┓┏┓╻╺┳┓┏━┓┏━┓╻╺┳┓   ┏━┓┏┓╻╻  ╻ ╻
# ┣━┫┃┗┫ ┃┃┣┳┛┃ ┃┃ ┃┃   ┃ ┃┃┗┫┃  ┗┳┛
# ╹ ╹╹ ╹╺┻┛╹┗╸┗━┛╹╺┻┛   ┗━┛╹ ╹┗━╸ ╹

.local/bin/chara:
  type: archive-file
  url: https://github.com/latipun7/charasay/releases/latest/download/chara-aarch64-linux-android.zip
  refreshPeriod: 132h

.termux/colors.properties:
  type: file
  url: https://github.com/catppuccin/termux/raw/main/Mocha/colors.properties
  refreshPeriod: 132h

.termux: # font.ttf
  type: archive
  url: https://drive.google.com/uc?export=download&id=1oKvdW1-7xrwOkyUqRiLjTK0KLDe2qNIZ
  refreshPeriod: 132h
{{- end }}
