.local/share/ansi-arts:
  type: git-repo
  url: https://github.com/latipun7/ansi-arts.git
  refreshPeriod: 744h

.config/bat/themes:
  type: archive
  url: https://api.github.com/repos/catppuccin/bat/tarball
  stripComponents: 1
  refreshPeriod: 168h
  include: ["*/*.tmTheme"]

{{ if ne .chezmoi.os "windows" -}}
# ╻ ╻┏┓╻╻╻ ╻   ┏━┓┏┓╻╻  ╻ ╻
# ┃ ┃┃┗┫┃┏╋┛   ┃ ┃┃┗┫┃  ┗┳┛
# ┗━┛╹ ╹╹╹ ╹   ┗━┛╹ ╹┗━╸ ╹

.local/bin/fnm:
  # NOTE: workaround of https://github.com/actions/upload-artifact/issues/38
  type: file
  url: {{ template "fnm-download-url" . }}
  executable: true
  refreshPeriod: 168h
  filter:
    command: gzip
    args: ["--decompress", "--to-stdout", "--suffix", ".zip"]

.config/btop/themes/catppuccin-mocha.theme:
  type: file
  url: https://github.com/catppuccin/btop/raw/main/catppuccin_mocha.theme
  refreshPeriod: 168h

# oh-my-zsh
.local/share/oh-my-zsh:
  type: git-repo
  url: https://github.com/ohmyzsh/ohmyzsh.git
  clone:
    args: ["--depth", "1"]
  pull:
    args: ["--dry-run"] # update with `omz update`

.local/share/omz-custom/themes/powerlevel10k:
  type: archive
  url: https://api.github.com/repos/romkatv/powerlevel10k/tarball/{{ (gitHubLatestRelease "romkatv/powerlevel10k").TagName }}
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.local/share/omz-custom/plugins/zsh-completions:
  type: archive
  url: https://api.github.com/repos/zsh-users/zsh-completions/tarball
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.local/share/omz-custom/plugins/zsh-syntax-highlighting:
  type: archive
  url: https://api.github.com/repos/zsh-users/zsh-syntax-highlighting/tarball
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.local/share/omz-custom/plugins/zsh-autosuggestions:
  type: archive
  url: https://api.github.com/repos/zsh-users/zsh-autosuggestions/tarball
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.local/share/omz-custom/plugins/zsh-autocomplete:
  type: archive
  url: https://github.com/marlonrichert/zsh-autocomplete/archive/d8bfbef46efc54c1189010a3b70d501b44487504.zip
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

# LunarVim
.local/share/lunarvim/lvim:
  type: git-repo
  url: https://github.com/LunarVim/LunarVim.git
  clone:
    args: ["--branch", "rolling", "--depth", "1"]
  pull:
    args: ["--dry-run"] # Update via `lvim +LvimUpdate`

# oh-my-tmux
.local/share/oh-my-tmux:
  type: git-repo
  url: https://github.com/gpakosz/.tmux.git
  refreshPeriod: 168h
  clone:
    args: ["--depth", "1"]
  pull:
    args: ["--dry-run"] # update/pull manually
{{ end -}}

{{ if .is_linux_gui -}}
# ╻  ╻┏┓╻╻ ╻╻ ╻   ┏━╸╻ ╻╻   ┏━┓┏┓╻╻  ╻ ╻
# ┃  ┃┃┗┫┃ ┃┏╋┛   ┃╺┓┃ ┃┃   ┃ ┃┃┗┫┃  ┗┳┛
# ┗━╸╹╹ ╹┗━┛╹ ╹   ┗━┛┗━┛╹   ┗━┛╹ ╹┗━╸ ╹

.config/kitty/themes/catppuccin:
  type: archive
  url: https://api.github.com/repos/catppuccin/kitty/tarball
  stripComponents: 1
  refreshPeriod: 168h
  include: ["*/*.conf"]

.local/share/fcitx5/themes: # Catppuccin
  type: archive
  url: https://api.github.com/repos/catppuccin/fcitx5/tarball
  stripComponents: 1
  refreshPeriod: 744h
  include: ["*/Catppuccin/**"]
{{- end }}

{{ if .is_server -}}
# ┏━┓┏━╸┏━┓╻ ╻┏━╸┏━┓   ┏━┓┏┓╻╻  ╻ ╻
# ┗━┓┣╸ ┣┳┛┃┏┛┣╸ ┣┳┛   ┃ ┃┃┗┫┃  ┗┳┛
# ┗━┛┗━╸╹┗╸┗┛ ┗━╸╹┗╸   ┗━┛╹ ╹┗━╸ ╹

.local/bin/godns:
  type: file
  url: {{ template "godns-download-url" . }}
  executable: true
  refreshPeriod: 168h
  filter:
    command: tar
    args: ["--extract", "--gzip", "--file", "/dev/stdin", "--to-stdout", "godns"]

www/adminer/adminer.php:
  type: file
  url: https://www.adminer.org/latest-en.php
  refreshPeriod: 744h

www/adminer/adminer.css:
  type: file
  url: https://raw.githubusercontent.com/Niyko/Hydra-Dark-Theme-for-Adminer/master/adminer.css
  refreshPeriod: 744h

www/adminer: # plugins
  type: archive
  url: "https://api.github.com/repos/vrana/adminer/tarball"
  stripComponents: 1
  refreshPeriod: 744h
  include: ["*/plugins/**"]
{{- end }}

{{ if eq .chezmoi.os "windows" -}}
# ╻ ╻╻┏┓╻╺┳┓┏━┓╻ ╻┏━┓   ┏━┓┏┓╻╻  ╻ ╻
# ┃╻┃┃┃┗┫ ┃┃┃ ┃┃╻┃┗━┓   ┃ ┃┃┗┫┃  ┗┳┛
# ┗┻┛╹╹ ╹╺┻┛┗━┛┗┻┛┗━┛   ┗━┛╹ ╹┗━╸ ╹

.local/bin: # fnm.exe
  type: archive
  url: {{ template "fnm-download-url" . }}
  refreshPeriod: 168h

.local/bin/jq.exe:
  type: file
  url: https://github.com/stedolan/jq/releases/latest/download/jq-win64.exe
  executable: true
  refreshPeriod: 744h
{{- end }}

{{ if eq .chezmoi.os "android" -}}
# ┏━┓┏┓╻╺┳┓┏━┓┏━┓╻╺┳┓   ┏━┓┏┓╻╻  ╻ ╻
# ┣━┫┃┗┫ ┃┃┣┳┛┃ ┃┃ ┃┃   ┃ ┃┃┗┫┃  ┗┳┛
# ╹ ╹╹ ╹╺┻┛╹┗╸┗━┛╹╺┻┛   ┗━┛╹ ╹┗━╸ ╹

.termux/colors.properties:
  type: file
  url: https://github.com/catppuccin/termux/raw/main/Mocha/colors.properties
  refreshPeriod: 168h

.termux: # font.ttf
  type: archive
  url: https://drive.google.com/uc?export=download&id=1oKvdW1-7xrwOkyUqRiLjTK0KLDe2qNIZ
  refreshPeriod: 168h
{{- end }}
