.local/share/ansi-arts:
  type: git-repo
  url: https://github.com/latipun7/ansi-arts.git
  refreshPeriod: 744h

{{ if ne .chezmoi.os "windows" -}}
# ╻ ╻┏┓╻╻╻ ╻   ┏━┓┏┓╻╻  ╻ ╻
# ┃ ┃┃┗┫┃┏╋┛   ┃ ┃┃┗┫┃  ┗┳┛
# ┗━┛╹ ╹╹╹ ╹   ┗━┛╹ ╹┗━╸ ╹

.local/bin/fnm:
  # NOTE: workaround of https://github.com/actions/upload-artifact/issues/38
  type: file
  url: {{ template "fnm-download-url" . }}
  executable: true
  refreshPeriod: 168h
  filter:
    command: gzip
    args: ["--decompress", "--to-stdout", "--suffix", ".zip"]

.config/bat/themes:
  type: archive
  url: https://api.github.com/repos/catppuccin/bat/tarball
  stripComponents: 1
  refreshPeriod: 168h
  include: ["*/*.tmTheme"]

.config/bpytop/themes/catppuccin-mocha.theme:
  type: file
  url: https://github.com/catppuccin/btop/raw/main/catppuccin_mocha.theme
  refreshPeriod: 168h

.local/share/mc/skins/dracula.ini:
  type: file
  url: https://raw.github.com/dracula/midnight-commander/master/skins/dracula.ini
  refreshPeriod: 168h

.local/share/mc/skins/dracula256.ini:
  type: file
  url: https://raw.github.com/dracula/midnight-commander/master/skins/dracula256.ini
  refreshPeriod: 168h

.local/share/omz-custom/themes/powerlevel10k:
  type: archive
  url: https://api.github.com/repos/romkatv/powerlevel10k/tarball/v{{ template "github-latest-tag" list "romkatv/powerlevel10k" .chezmoi.os }}
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.local/share/omz-custom/plugins/zsh-completions:
  type: archive
  url: https://api.github.com/repos/zsh-users/zsh-completions/tarball
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.local/share/omz-custom/plugins/zsh-syntax-highlighting:
  type: archive
  url: https://api.github.com/repos/zsh-users/zsh-syntax-highlighting/tarball
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.local/share/omz-custom/plugins/zsh-autosuggestions:
  type: archive
  url: https://api.github.com/repos/zsh-users/zsh-autosuggestions/tarball
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

.local/share/omz-custom/plugins/zsh-autocomplete:
  type: archive
  url: https://api.github.com/repos/marlonrichert/zsh-autocomplete/tarball
  exact: true
  stripComponents: 1
  refreshPeriod: 168h

{{    if not .is_server -}}
# ╺┳┓┏━╸┏━┓╻┏ ╺┳╸┏━┓┏━┓   ┏━┓┏┓╻╻  ╻ ╻
#  ┃┃┣╸ ┗━┓┣┻┓ ┃ ┃ ┃┣━┛   ┃ ┃┃┗┫┃  ┗┳┛
# ╺┻┛┗━╸┗━┛╹ ╹ ╹ ┗━┛╹     ┗━┛╹ ╹┗━╸ ╹

.config/kitty/themes/dracula.conf:
  type: file
  url: https://github.com/dracula/kitty/raw/master/dracula.conf
  refreshPeriod: 168h

.config/kitty/themes/tokyonight.conf:
  type: file
  url: https://github.com/folke/tokyonight.nvim/raw/main/extras/kitty_tokyonight_storm.conf
  refreshPeriod: 168h

.config/kitty/themes/catppuccin.conf:
  type: file
  url: https://github.com/catppuccin/kitty/raw/main/catppuccin.conf
  refreshPeriod: 168h

.local/share/fcitx5/themes/Catppuccin:
  type: archive
  url: "https://api.github.com/repos/catppuccin/fcitx5/tarball"
  refreshPeriod: 744h
  stripComponents: 2
  include: ["*", "*/Catppuccin", "*/Catppuccin/*"]
{{-   end }}

{{    if .is_server -}}
# ┏━┓┏━╸┏━┓╻ ╻┏━╸┏━┓   ┏━┓┏┓╻╻  ╻ ╻
# ┗━┓┣╸ ┣┳┛┃┏┛┣╸ ┣┳┛   ┃ ┃┃┗┫┃  ┗┳┛
# ┗━┛┗━╸╹┗╸┗┛ ┗━╸╹┗╸   ┗━┛╹ ╹┗━╸ ╹

.local/bin/godns:
  type: file
  url: {{ template "godns-download-url" . }}
  executable: true
  refreshPeriod: 168h
  filter:
    command: tar
    args: ["--extract", "--gzip", "--file", "/dev/stdin", "--to-stdout", "godns"]

www/adminer/adminer.php:
  type: file
  url: https://www.adminer.org/latest-en.php
  refreshPeriod: 744h

www/adminer/adminer.css:
  type: file
  url: https://raw.githubusercontent.com/Niyko/Hydra-Dark-Theme-for-Adminer/master/adminer.css
  refreshPeriod: 744h

www/adminer/plugins:
  type: archive
  url: "https://api.github.com/repos/vrana/adminer/tarball"
  refreshPeriod: 744h
  stripComponents: 2
  include: ["*", "*/plugins", "*/plugins/*.php", "*/plugins/drivers", "*/plugins/drivers/*.php"]
{{-   end }}
{{- end }}

{{ if eq .chezmoi.os "windows" -}}
# ╻ ╻╻┏┓╻╺┳┓┏━┓╻ ╻┏━┓   ┏━┓┏┓╻╻  ╻ ╻
# ┃╻┃┃┃┗┫ ┃┃┃ ┃┃╻┃┗━┓   ┃ ┃┃┗┫┃  ┗┳┛
# ┗┻┛╹╹ ╹╺┻┛┗━┛┗┻┛┗━┛   ┗━┛╹ ╹┗━╸ ╹

.local/bin:
  type: archive
  url: {{ template "fnm-download-url" . }}
  refreshPeriod: 168h

.local/bin/jq.exe:
  type: file
  url: https://github.com/stedolan/jq/releases/latest/download/jq-win64.exe
  executable: true
  refreshPeriod: 744h
{{- end }}
