#!/usr/bin/env bash

# ▄▖    ▘             ▗
# ▙▖▛▌▌▌▌▛▘▛▌▛▌▛▛▌█▌▛▌▜▘▛▘
# ▙▖▌▌▚▘▌▌ ▙▌▌▌▌▌▌▙▖▌▌▐▖▄▌

[ -f ~/.zshenv ] && source ~/.zshenv

# XOrg
export USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
export USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"
export ALTUSERXSESSION="$XDG_CACHE_HOME/X11/Xsession"
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

# GTK
export GTK_RC_FILES="$XDG_CONFIG_HOME/gtk-1.0/gtkrc"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"

# ▄▖  ▗     ▗     ▗
# ▌▌▌▌▜▘▛▌▛▘▜▘▀▌▛▘▜▘
# ▛▌▙▌▐▖▙▌▄▌▐▖█▌▌ ▐▖

xrdb -merge ~/.local/share/Xresources
