#!/usr/bin/env bash
# shellcheck disable=1090

# ▄▖    ▘             ▗
# ▙▖▛▌▌▌▌▛▘▛▌▛▌▛▛▌█▌▛▌▜▘▛▘
# ▙▖▌▌▚▘▌▌ ▙▌▌▌▌▌▌▙▖▌▌▐▖▄▌

# Gnome Keyring
eval "$(gnome-keyring-daemon --start)"
export SSH_AUTH_SOCK

# XOrg
export USERXSESSION="$XDG_CACHE_HOME/X11/xsession"
export USERXSESSIONRC="$XDG_CACHE_HOME/X11/xsessionrc"
export ALTUSERXSESSION="$XDG_CACHE_HOME/X11/Xsession"
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

# GTK
export GTK_RC_FILES="$XDG_CONFIG_HOME/gtk-1.0/gtkrc"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc"

# IM
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export SDL_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx

# Todo
export TODO_PATH="$HOME/Documents/todo"

# Uniform look for Qt and GTK apps
# https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications
export QT_QPA_PLATFORMTHEME=qt5ct

# ▄▖  ▗     ▗     ▗
# ▌▌▌▌▜▘▛▌▛▘▜▘▀▌▛▘▜▘
# ▛▌▙▌▐▖▙▌▄▌▐▖█▌▌ ▐▖

xrdb -merge ~/.local/share/Xresources
