#!/usr/bin/env bash

HYPRGAMEMODE=$(hyprctl getoption animations:enabled | sed -n '2p' | awk '{print $2}')

if [ "$HYPRGAMEMODE" = 1 ]; then
  hyprctl --batch "\
    keyword animations:enabled 0;\
    keyword decoration:drop_shadow 0;\
    keyword decoration:blur 0;\
    keyword general:gaps_in 0;\
    keyword general:gaps_out 0;\
    keyword general:border_size 1;\
    keyword decoration:rounding 0"
  pkill -fx "bash $XDG_CONFIG_HOME/hypr/scripts/random-wallpapers /home/data/pictures/wallpapers" &>/dev/null
  sleep 0.3 && swww img /home/data/pictures/unused-wallpapers/cat-pacman.png
  exit
fi

pkill -fx "bash $XDG_CONFIG_HOME/hypr/scripts/random-wallpapers /home/data/pictures/wallpapers" &>/dev/null
sleep 0.3 && bash ~/.config/hypr/scripts/random-wallpapers /home/data/pictures/wallpapers &
hyprctl reload
