#!/usr/bin/env bash

function open() {
  WORKSPACE=$(hyprctl clients -j | jq -rec ".[] | select(.workspace.name == \"special:$1\") | .workspace.name")

  if [ -z "$WORKSPACE" ]; then
    hyprctl dispatch -- exec "${@:2}"
    if [[ "$1" == "chat" ]]; then
      sleep 3.9 # NOTE: discord is long to open
    else
      sleep 0.9
    fi
    hyprctl dispatch togglespecialworkspace "$1"
  elif [ "$WORKSPACE" == "special:$1" ]; then
    hyprctl dispatch togglespecialworkspace "$1"
  fi
}

function main() {
  case "$1" in
    chat)
      open "$1" discord
      ;;
    term)
      open "$1" wezterm start --always-new-process --class scratch-term
      ;;
    calc)
      open "$1" qalculate-gtk
      ;;
    *)
      echo "no scratchpad with the name of $1"
      ;;
  esac
}

main "$@"
