#!/usr/bin/env bash

function icon() {
  STATUS="$(rfkill list | sed -n 2p | awk '{print $3}')"

  if [[ $STATUS == "no" ]]; then
    echo '{"icon": "󰀞", "class": ""}'
  else
    echo '{"icon": "󰀝", "class": "airplane-mode"}'
  fi
}

function toggle() {
  STATUS="$(rfkill list | sed -n 2p | awk '{print $3}')"

  if [[ $STATUS == "no" ]]; then
    rfkill block all
    notify-send --urgency=normal -i airplane-mode-symbolic "Airplane Mode" "Airplane mode has been turned on!"
  else
    rfkill unblock all
    notify-send --urgency=normal -i airplane-mode-disabled-symbolic "Airplane Mode" "Airplane mode has been turned off!"
  fi
}

if [[ $1 == "toggle" ]]; then
  toggle
else
  # initial value
  echo '{"icon": "󰀞", "class": ""}'

  while true; do
    STATUS="$(rfkill list | sed -n 2p | awk '{print $3}')"
    icon
    sleep 3
  done
fi
