#!/usr/bin/env bash

function clamp {
  min=1
  max=5
  val=$1
  python -c "print(max($min, min($val, $max)))"
}

direction=$1
current=$2
if test "$direction" = "up"; then
  target=$(clamp $((current + 1)))
  echo "jumping to $target"
  hyprctl dispatch workspace "$target"
elif test "$direction" = "down"; then
  target=$(clamp $((current - 1)))
  echo "jumping to $target"
  hyprctl dispatch workspace "$target"
fi
