#!/usr/bin/env bash

function toggle() {
  status=$(rfkill -J | jq -r '.rfkilldevices[] | select(.type == "wlan") | .soft' | head -1)

  if [ "$status" = "unblocked" ]; then
    rfkill block wlan
  else
    rfkill unblock wlan
  fi
}

if [ "$1" = "toggle" ]; then
  toggle
else
  # initial value
  echo '{"ssid": "WiFi", "icon": "󰤯", "color": "#9299b2", "class": ""}'

  while true; do
    status=$(nmcli g | tail -n 1 | awk '{print $1}')
    signal=$(nmcli -f in-use,signal dev wifi | rg "\*" | awk '{ print $2 }')
    ssid=$(nmcli -t -f NAME connection show --active | head -n1 | sed 's/\"/\\"/g')

    icons=("󰤯" "󰤟" "󰤢" "󰤥" "󰤨")

    if [ "$status" = "disconnected" ]; then
      icon="󰤭"
      color="#9399b2"
      class=""
    else
      level=$(awk -v n="$signal" 'BEGIN{print int((n-1)/20)}')
      if [ "$level" -gt 4 ]; then
        level=4
      fi

      icon=${icons[$level]}
      color="#cba6f7"
      class="wifi-connected"
    fi

    echo '{"ssid": "'"$ssid"'", "icon": "'"$icon"'", "color": "'"$color"'", "class": "'"$class"'"}'

    sleep 3
  done
fi
