#!/usr/bin/env bash

# shellcheck disable=2016
socat -u "UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - |
  stdbuf -o0 grep '^urgent>>' |
  stdbuf -o0 awk -F '>>|,' '{print $2}'
