"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

### Custom ###

[[mgr.prepend_keymap]]
on = "!"
run = 'shell --block -- $SHELL -l'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on = "e"
run = 'shell --block "$EDITOR"'
desc = "Open editor for current working directory"

[[mgr.prepend_keymap]]
on = "i"
run = 'shell --block -- bat --paging=never --color=always --style=numbers,grid "$1" | less -Ri'
desc = "Show text on pager"

### Plugins ###

[[mgr.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on = "<Tab>"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[mgr.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on = "C"
run = "plugin ouch zip"
desc = "Compress with ouch"

[[mgr.prepend_keymap]]
on = "M"
run = "plugin mount"
desc = "Mount with fuse"

[[mgr.prepend_keymap]]
on = ["g", "i"]
run = "plugin lazygit"
desc = "Run lazygit"

### Bookmarks ###

[[mgr.prepend_keymap]]
on = ["g", "H"]
run = "cd ~/.local/share/chezmoi"
desc = "Go to chezmoi source directory"
