"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[manager.prepend_keymap]]
on = ["<C-s>"]
run = 'shell "$SHELL -l" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = ["e"]
run = 'shell "$EDITOR" --block --confirm'
desc = "Open editor for current working directory"

[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[manager.prepend_keymap]]
on = ["i"]
run = "plugin --sync max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on = ["F"]
run = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on = ["f", "g"]
run = "plugin fzf-fg"
desc = "find file by content (fuzzy match)"

[[manager.prepend_keymap]]
on = ["f", "G"]
run = "plugin fzf-fg --args='rg'"
desc = "find file by content (ripgrep match)"

[[manager.prepend_keymap]]
on = ["f", "f"]
run = "plugin fzf-fg --args='fzf'"
desc = "find file by filename"

[[manager.prepend_keymap]]
on = ["g", "H"]
run = "cd ~/.local/share/chezmoi"
desc = "Go to chezmoi source directory"
