"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

### Custom ###

[[manager.prepend_keymap]]
on = "!"
run = 'shell "$SHELL -l" --block'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = "e"
run = 'shell "$EDITOR" --block'
desc = "Open editor for current working directory"

[[manager.prepend_keymap]]
on = "i"
run = "shell 'bat --paging=never --color=always --style=numbers,grid \"$0\" | less -Ri' --block"
desc = "Show text on pager"

### Plugins ###

[[manager.prepend_keymap]]
on = ["c", "m"]
run = "plugin chmod"
desc = "Chmod on selected files"

[[manager.prepend_keymap]]
on = "<Tab>"
run = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

[[manager.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on = "C"
run = "plugin ouch zip"
desc = "Compress with ouch"

[[manager.prepend_keymap]]
on = "M"
run = "plugin mount"

### Bookmarks ###

[[manager.prepend_keymap]]
on = ["g", "H"]
run = "cd ~/.local/share/chezmoi"
desc = "Go to chezmoi source directory"
