"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 3, 4]
sort_by = "natural"
show_hidden = true

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" },
  { mime = "audio/*", run = "exifaudio" },

  # Archive previewer
  { mime = "application/*zip", run = "ouch" },
  { mime = "application/x-{tar,bzip*,7z-compressed,xz,rar,iso9660-image}", run = "ouch" },
]

[opener]
extract = [
  { run = 'ouch d -y "%*"', desc = "Extract here with ouch", for = "windows" },
  { run = 'ouch d -y "$@"', desc = "Extract here with ouch", for = "unix" },
]
