tap "homebrew/bundle"
tap "homebrew/core"

# Development Utilities
brew "fontforge"
brew "gcc@9"
brew "imagemagick"
brew "shellcheck"

# Libraries
brew "libsecret"

# Replacements
brew "bat" # cat
brew "lsd" # ls
brew "zsh" # shell

# Utilities
brew "fzf"
brew "htop"
brew "midnight-commander"

# Games / Fun
brew "cmatrix"
brew "cowsay"
brew "fortune"
brew "lolcat"
brew "neofetch"
brew "ponysay", args: ["HEAD"]
brew "sl"
