tap "cjbassi/ytop"
tap "homebrew/bundle"
tap "homebrew/core"
tap "linuxbrew/xorg"

# Development Utilities
brew "fontforge"
brew "gcc@9"
brew "imagemagick"
brew "pkg-config"
brew "shellcheck"

# Libraries
brew "libsecret"

# Replacements
brew "bat"    # cat
brew "lsd"    # ls
brew "neovim" # vim
brew "zsh"    # shell

# Utilities
brew "fzf"
brew "lm-sensors"
brew "midnight-commander"
brew "ytop"

# Games / Fun
brew "cmatrix"
brew "cowsay"
brew "fortune"
brew "lolcat"
brew "neofetch"
brew "ponysay", args: ["HEAD"]
brew "sl"
