[tools]
bitwarden = "latest"
chezmoi = "latest"
glow = "latest"
node = "latest"
rust = "latest"
usage = "latest"

[settings]
registry_floating = true

[settings.cargo]
binstall_quickinstall = true

[settings.aqua]
registry_cache_ttl = "24h"
